C:\VulkanSDK\1.4.309.0\Bin\glslc.exe ../shaders/simple_shader.vert -o ../shaders/simple_shader.vert.spv
C:\VulkanSDK\1.4.309.0\Bin\glslc.exe ../shaders/simple_shader.frag -o ../shaders/simple_shader.frag.spv
C:\VulkanSDK\1.4.309.0\Bin\glslc.exe ../shaders/point_light.vert -o ../shaders/point_light.vert.spv
C:\VulkanSDK\1.4.309.0\Bin\glslc.exe ../shaders/point_light.frag -o ../shaders/point_light.frag.spv
C:\VulkanSDK\1.4.309.0\Bin\glslc.exe ../shaders/gBuffer.vert -o ../shaders/gBuffer.vert.spv
C:\VulkanSDK\1.4.309.0\Bin\glslc.exe ../shaders/gBuffer.frag -o ../shaders/gBuffer.frag.spv
C:\VulkanSDK\1.4.309.0\Bin\glslc.exe ../shaders/LightningPassDeffered.vert -o ../shaders/LightningPassDeffered.vert.spv
C:\VulkanSDK\1.4.309.0\Bin\glslc.exe ../shaders/LightningPassDeffered.frag -o ../shaders/LightningPassDeffered.frag.spv
C:\VulkanSDK\1.4.309.0\Bin\glslc.exe ../shaders/billboard.vert -o ../shaders/billboard.vert.spv
C:\VulkanSDK\1.4.309.0\Bin\glslc.exe ../shaders/billboard.frag -o ../shaders/billboard.frag.spv